---
- hosts: zabbix-agents
  tasks:
  - name: role basicSetup
    include_role:
      name: basicSetup

  - debug:
      var: group_names

  - name: role Zabbix Agent
    include_role:
      name: zabbix-agent

  - name: deploy disk performance
    include_tasks: tasks/deploy_disk_performance.yml

  - name: deploy tcp monitoring
    include_tasks: tasks/deploy_tcp.yml

  - name: deploy raspberry CPU monitoring
    include_tasks: tasks/deploy_raspberry_cpu.yml
    when: "'raspberry-pis' in  group_names"

  handlers:
  - name: restart agent
    service:
      name: zabbix-agent
      state: restarted

