---
- name: GLUSTERFS | Install git
  apt:
    name: git
    state: present

- name: GLUSTERFS | Download gstatus
  get_url:
    url: https://github.com/gluster/gstatus/releases/latest/download/gstatus
    dest: /usr/local/bin/gstatus

- name: GLUSTERFS | Be executed
  file:
    path: /usr/local/bin/gstatus
    mode: 755

- name: GLUSTERFS | Copy user parameters
  copy:
    src: module-templates/zabbix-glusterfs/glusterfs.conf
    dest: /etc/zabbix/zabbix_agentd.d/
    mode: 0644
  notify:
    - restart agent

- name: GLUSTERFS | Copy binary
  copy:
    src: module-templates/zabbix-glusterfs/gstatus_discovery.py
    dest: /usr/local/bin/
    mode: 0755

- name: GLUSTERFS | Add sudoers user zabbix
  copy: 
    dest: /etc/sudoers.d/monitor-glusterfs
    content: "zabbix ALL=(ALL) NOPASSWD: /usr/local/bin/gstatus_discovery.py\n"
    mode: 0440
    
