---
- copy:
    src: module-templates/zabbix-tcp/zabbix_agentd.d/userparameter_tcpstats.conf
    dest: /etc/zabbix/zabbix_agentd.d/
    mode: 0644
  notify:
    - restart agent

- copy:
    src: module-templates/zabbix-tcp/bin/tcpstats.sh
    dest: /usr/local/bin/
    mode: 0755

