---
- copy:
    src: module-templates/disk-performance/userparameter_diskstats.conf
    dest: /etc/zabbix/zabbix_agentd.d/
    mode: 0644
  notify:
    - restart agent

- copy:
    src: module-templates/disk-performance/lld-disks.py
    dest: /usr/local/bin/
    mode: 0755

